import type { Metadata } from "next";
import { Bebas_Neue, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${bebasNeue.variable} ${geistMono.variable} h-full scroll-smooth overflow-x-hidden bg-[#0D0D0D] antialiased`}
    >
      <body className="min-h-full flex flex-col items-center px-4 py-10 sm:px-6 md:px-8 md:py-[80px] font-sans bg-linear-to-b from-[#080808] via-[#0A0A0A]/30 via-19% to-[#0D0D0D]/0">
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
